### ISSUE TITLE
Reauthenticate user

### ISSUE THREAD

**Issue by retwas** [SchneiderInfosystems/FB4D#110]
Assuming we are on a mobile app. The user can create an account the first time he launch it, but the second time, he need to use the app without login manually.

How can I re-authenticate user if I only save mail and refresh token ?

Should I store the password, and login user ? I would prefer to not do it.

Thanks

**Comment by SchneiderInfosystems** [comment]
Please write such questions next time into our discussion board, because this is not a bug report, but a question about how to use the library.

Of course, **you should never save a customer password in your application.** This is a principal IT Security rule which shall never be broken!

There are several given sample application which does exactly your requested workflow by storing the last refresh token and re-login with the last stored refresh token. 

E.g. the 2nd example of RT DB Samples uses the Self-Registration-Workflow which offers this feature:
See https://github.com/SchneiderInfosystems/FB4D/wiki/RT-DB-Sample-Applications#2nd-example-one-string-for-each-registered-user

Check this description of how to use the lastRefreshToken in the self-registration workflow:
https://github.com/SchneiderInfosystems/FB4D/wiki/Self-Registration-Workflow

If you don't like to use this GUI framework, you can implement this function by yourself. For this purpose, you have to use the method `IFirebaseAuthentication.RefreshToken(const LastRefreshToken: string; OnTokenRefresh: TOnTokenRefresh; OnError: TOnRequestError)`

**Aditional hint:** The last refresh token is not that critical as a customer password but if you plan to release your app in a store or share it widely, **I recommend nevertheless encrypting/decrypting the last refresh token when storing it in a local file in order to prevent, that an attacker cannot misuse your stored token**.
