### ISSUE TITLE
Firebase Authenticate using service account

### ISSUE THREAD

**Issue by DreamHunterUA** [SchneiderInfosystems/FB4D#146]
Hi. Are you plannin to add this feature to FB4D? It woulbe great. Thanks

**Comment by SchneiderInfosystems** [comment]
This is a feature request and you are the first with this request.

In order to estimate an analysis for feasibility and implementation effort I need your commitment that you are willing to cover at least half of my development costs for this enhancement. Do you have a commercial project and are you willing to pay for a development in Switzerland?
