### ISSUE TITLE
Firebase Cloud Messaging functionality

### ISSUE THREAD

**Issue by RaySa74** [SchneiderInfosystems/FB4D#25]
It would be great if FB4D integrate Cloud Messaging functionality into it. Where you can send messages using FB4D to android and IOS devices?
thanks

**Comment by SchneiderInfosystems** [comment]
The Firebase Cloud Messaging does offer a REST API. That is why such an extension is currently not possible. Since Delphi 10.3.2 for the Android platform only, the Push Notification based on FCM can be used. But I had trouble to test it. See my open questions here:
https://stackoverflow.com/questions/57819964/example-from-marco-cantu-firebase-push-notifications-on-delphi-10-3-2
Until today I did not get an answer from Embarcadeor to my questions.
And of course, this solution is just for mobile platforms available because it calls the Firebase library on android and (probably in future) also on iOS. 
For desktop platform as Windows and macOS or Linux, this solution will not be an option.
Currently, I recommend to build your own message system based on the Real-Time-DB by using the listener.

**Comment by SchneiderInfosystems** [comment]
In the meantime, I get the description for the new solution built in Delphi 10.3.2 from Embarcadero:

 http://docwiki.embarcadero.com/RADStudio/Rio/en/Firebase_Android_Support

Note: This solution works for Android only (and in the future perhaps for iOS). Desktop platforms as Windows / MacOS / Linux are not supported by the native Firebase Library from Google. The TPushService delivered by Delphi RTL bases on the native Firebase Library.
