### ISSUE TITLE
Parameter has same name as property

### ISSUE THREAD

**Issue by cbugge** [SchneiderInfosystems/FB4D#31]
In Unit FB4D.Authentification

constructor TFirebaseAuthentication.Create(const ApiKey: string);
begin
  inherited Create;
  fApiKey := ApiKey;
end;

the parameter ApiKey has the same name as the property ApiKey.
Perhaps better: Rename parameter to aApiKey:

constructor TFirebaseAuthentication.Create(const aApiKey: string);
begin
  inherited Create;
  fApiKey := aApiKey;
end;

Greetings from Christian

**Comment by SchneiderInfosystems** [comment]
This is in my opinion just a convention. Within the constructor the local variable in the parameter has higher visibility than the property of the same name. Because we do need to access the property in the constructor, there is no benefit to distinguish the name. Of course, the code would be more readable by using aApiKey but I had to refactor more than this single point
