### ISSUE TITLE
Doubt about TRealTimeDB.ListenForValueEvents in event ListenEvent, why I receive every hour the change notification?

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#56]
Hello, I have a doubt, I am receiving in the ListenEvent event of the TRealTimeDB.ListenForValueEvents a change notification every 1 hour. 

I am sure that nobody has changed the data in the realtime database.

I have no timer or similar in my code, I have added a breakpoint in the procedure of the ListenEvent event, and I can see in the notifications of every hour, that the call stack is similar to real change notifications, I do not understand this behaviour.

Is it correct that I receive a change notification every 1 hour?, and why?. 

Thank you.

**Comment by SchneiderInfosystems** [comment]
This is a normal and expected behavior of the ListenEvent because all hours the Firebase token is expired and needs to be renewed. This will be done automatically by the FB4D.  Pls read this: https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Reference-IRealTimeDB#install-a-listener-for-changes-in-a-json-node

**Comment by macc2010** [comment]
Thank you very much. :-)
