### ISSUE TITLE
Cloud Firestore Limit on request

### ISSUE THREAD

**Issue by leonardoaa** [SchneiderInfosystems/FB4D#59]
Hi Guys, are u ok?

I have a doubt (I believe that is not a bug, but don't found a solution). 

When I request a collection from CloudFirestore, just first 20 docs appears.

My collection have 50+ docs, 
![image](https://user-images.githubusercontent.com/14091683/105426387-cf85d080-5c29-11eb-9dc0-8c50bbf74cb4.png)

But when get from component

![image](https://user-images.githubusercontent.com/14091683/105426524-1ecc0100-5c2a-11eb-8e03-f49a71ce4c6c.png)

The request is correct, this first 20 docs exists in my collection

mt request code

![image](https://user-images.githubusercontent.com/14091683/105426623-4c18af00-5c2a-11eb-8d86-1a8e91619052.png)

same result with example code

what am I doing wrong? Could you help me, friends?

Tks a Lot :)

**Comment by SchneiderInfosystems** [comment]
This is a very valuable finding. Thanks for this report! 

I could reproduce your finding and see that there is a limitation in the underlying Firestore Rest API. Unfortunately, I have not seen any specification in the Firestore documentation about this limitation to 20 documents.

 Get the change to understand the following solutions:
1.) You can increasre the page size to e.g. 50 documents (see FB4DDemoFmx.pas at line 1014):
TQueryParams.CreateQueryParams(Query).AddPageSize(50);
2.) You can repeatedly call IFirestoreDatabase.Get by overtaking the last PageToken from the last Get in order to fetch the next series of documents. If the new property IFirestoreDocuments.MorePagesToLoad becomes false, you have fetched all documents. 

Please check the new solution carefully. Beginn the DemoFB4D Application to see all details which currently are still not documented in the Wiki.  I will do that soon. Please post your feedback from your tests here.

**Comment by leonardoaa** [comment]
Hi, I fixed with the first option, AddPageSize.... works correct for me! Tks a lot!
